[project]
name = "comfyui-zyd232-nodes"
description = "ComfyUI nodes including LLM Text Generation for any LLM server (multiple image/video/audio input, preset management, hide API-key, clean VRAM, auto-unload), Merge LoRA Stacks, Image Pixel Comparison, and other nodes for quality-of-life improvements."
version = "0.9.2"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/zyd232/ComfyUI-zyd232-Nodes"

[tool.comfy]
PublisherId = "zyd232"
DisplayName = "ComfyUI-zyd232-Nodes"
Icon = ""
